# encoding: utf-8
---
recipe:
  Rx: mkm
  description: >-
    A set of CJK rime input schemas.

install_files: >-
  lua/mkm/*.lua
  
patch_files:
  kagiroi.yaml:
    alphabet/3_dan/alphabet: "-qwertyuiopasdfghjkl;zxcvbnm\x60"
    alphabet/3_dan_hira/alphabet: "ょぁぃぅぇぉあいうえおかきくけこがぎぐげごさしすせそざじずぜぞたちつてとだぢづでどなにぬねのはひふへほばびぶべぼぱぴぷぺぽまみむめもやゆよらりるれろわゐ𛄟ゑをんゃっゕゖーゅabcdefghijklmnopqrstuvwxyz-;\x60"
  moran.schema.yaml:
    schema/dependencies/+:
      - kagiroi
      - mungyeong
    engine/segmentors/@before 6: affix_segmentor@kagiroi
    engine/processors/@before 3: lua_processor@*kagiroi/kagiroi_kana_speller
    engine/segmentors/@before 7: affix_segmentor@mungyeong
    engine/processors/@before 4: lua_processor@*mungyeong/mungyeong_hangul_speller
    engine/translators/+:
      - lua_translator@*kagiroi/kagiroi_translator
      - lua_translator@*mungyeong/mungyeong_translator
    kagiroi:
      prefix: ok
      tips: 〔カギロイ〕
      tag: kagiroi
      layout: romaji
      speller:
        __include: kagiroi:/alphabet/3_dan
    mungyeong:
      prefix: om
      tips: 〔문경〕
      tag: mungyeong
      layout: dubeolsik
    recognizer/patterns/kagiroi: '^(?:ok|\xE3\x81[\x81-\xBF]|\xE3\x82[\x80-\x9F]|\xE3\x83\xBC)(?:\xE3\x81[\x81-\xBF]|\xE3\x82[\x80-\x9F]|\xE3\x83\xBC|[a-z\-;])*$'
    recognizer/patterns/mungyeong: '^(?:om|(?:\xEA[\xB0-\xBF]|\xEB[\x80-\xBF]|\xEC[\x80-\xBF]|\xED[\x80-\x9D])[\x80-\xBF]|\xED\x9E[\x80-\xA3]|\xE3\x84[\xB1-\xBF]|\xE3\x85[\x80-\xA3])(?:(?:(?:\xEA[\xB0-\xBF]|\xEB[\x80-\xBF]|\xEC[\x80-\xBF]|\xED[\x80-\x9D])[\x80-\xBF]|\xED\x9E[\x80-\xA3]|\xE3\x84[\xB1-\xBF]|\xE3\x85[\x80-\xA3])|[a-zA-Z])*$'
  kagiroi.schema.yaml:
    engine/processors/@before 1: lua_processor@*mungyeong/mungyeong_hangul_speller
    engine/translators/@before 2: reverse_lookup_translator@moran
    engine/translators/@before 3: reverse_lookup_translator@mungyeong
    engine/filters/+:
      - lua_filter@*mkm/moran_aux_filter
    kagiroi/translator/input_mapping:
      - xform/^([^\x60]*)n$/$1ん$/
  mungyeong.schema.yaml:
    engine/processors/@before 2: lua_processor@*kagiroi/kagiroi_kana_speller
    engine/translators/@before 2: reverse_lookup_translator@kagiroi
    engine/translators/@before 3: reverse_lookup_translator@moran
    engine/filters/+:
      - lua_filter@*mkm/moran_aux_filter
    recognizer/patterns/mungyeong: '^(?:(?:\xEA[\xB0-\xBF]|\xEB[\x80-\xBF]|\xEC[\x80-\xBF]|\xED[\x80-\x9D])[\x80-\xBF]|\xED\x9E[\x80-\xA3]|\xE3\x84[\xB1-\xBF]|\xE3\x85[\x80-\xA3])(?:(?:(?:\xEA[\xB0-\xBF]|\xEB[\x80-\xBF]|\xEC[\x80-\xBF]|\xED[\x80-\x9D])[\x80-\xBF]|\xED\x9E[\x80-\xA3]|\xE3\x84[\xB1-\xBF]|\xE3\x85[\x80-\xA3])|[a-zA-Z\x60])*$'
    
