# encoding: utf-8
---
recipe:
  Rx: mkm
  description: >-
    A set of CJK rime input schemas.

install_files: >-
  lua/mkm/*.lua
  *.mkm.yaml
  
patch_files:
  kagiroi.yaml:
    alphabet/3_dan/alphabet: "-qwertyuiopasdfghjkl;zxcvbnm\x60"
    alphabet/3_dan_hira/alphabet: "ã‚‡ããƒã…ã‡ã‰ã‚ã„ã†ãˆãŠã‹ããã‘ã“ãŒããã’ã”ã•ã—ã™ã›ãã–ã˜ãšãœããŸã¡ã¤ã¦ã¨ã ã¢ã¥ã§ã©ãªã«ã¬ã­ã®ã¯ã²ãµã¸ã»ã°ã³ã¶ã¹ã¼ã±ã´ã·ãºã½ã¾ã¿ã‚€ã‚ã‚‚ã‚„ã‚†ã‚ˆã‚‰ã‚Šã‚‹ã‚Œã‚ã‚ã‚ğ›„Ÿã‚‘ã‚’ã‚“ã‚ƒã£ã‚•ã‚–ãƒ¼ã‚…abcdefghijklmnopqrstuvwxyz-;\x60"
  moran.schema.yaml:
    - moran.mkm:/patch
    - moran.custom:/patch?
  kagiroi.schema.yaml:
    - kagiroi.mkm:/patch
    - kagiroi.custom:/patch?
  mungyeong.schema.yaml:
    - mungyeong.mkm:/patch
    - mungyeong.custom:/patch?
